name: dotnet test

on: [push]

env:
  SOLUTION_PATH: 'Src\ChromeDriverUpdater\ChromeDriverUpdater.sln'
  PROJECT_PATH: 'Src\ChromeDriverUpdater\ChromeDriverUpdater.csproj'
  TEST_PROJECT_PATH: 'Src\ChromeDriverUpdater.Tests\ChromeDriverUpdater.Tests.csproj'

jobs:
  build:

    runs-on: 'windows-latest'
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: 'Restore packages'
        run: dotnet restore ${{ env.SOLUTION_PATH }}
      - name: 'Build project'
        run: dotnet build ${{ env.SOLUTION_PATH }} --no-restore --configuration Release
      - name: 'Test project'
        run: dotnet test ${{ env.TEST_PROJECT_PATH }} --no-restore --verbosity normal --logger trx --results-directory "TestResults-${{ matrix.dotnet-version }}"