name: dotnet test

on: [push]

env:
  PROJECT_PATH: 'Src\ChromeDriverUpdater\ChromeDriverUpdater.csproj'
  TEST_PROJECT_PATH: 'Src\ChromeDriverUpdater.Tests\ChromeDriverUpdater.Tests.csproj'

jobs:
  build:

    runs-on: 'windows-latest'

    steps:
      - uses: actions/checkout@v2
      - name: use dotnet
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '5.0.x'
      - name: use dotnet
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '6.0.x'
      - name: 'Restore packages'
        run: dotnet restore ${{ env.PROJECT_PATH }}
      - name: 'Build project'
        run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release
      - name: 'Restore packages'
        run: dotnet restore ${{ env.TEST_PROJECT_PATH }}
      - name: 'Build project'
        run: dotnet build ${{ env.TEST_PROJECT_PATH }} --no-restore --configuration Release
      - name: 'Test project'
        run: dotnet test ${{ env.TEST_PROJECT_PATH }} --no-restore --verbosity normal --logger trx