name: dotnet package

on: [push]

jobs:
  build:

    runs-on: 'windows-latest'
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '6.0.x'
      - name: Build
        run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release
      - name: Test
        run: dotnet test --no-restore --verbosity normal